name: Java CI

# list with singe event
on: [push]

jobs:
  build: #job_id is named build
    runs-on: ubuntu-latest #virtual environment that runs this build job

    steps:
    - uses: actions/checkout@v1 # some predefined action
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 # parameters that are required for the action 'actions/setup-java@v1'
    - name: Build with Maven
      # '-B' = non interactive batch mode
      # '--file pom.xml' = can be used if pom.xml is named differently, without '--file' mvn would look per default for pom.xml
      # 'package' = lifecycle just create jar   
      run: mvn -B package --file pom.xml
    - name: Run Sonarqube
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
      
      
